[[constraint]]
  name = "cloud.google.com/go"
  version = ">=0.7.0, <1.0.0"

[[constraint]]
  name = "github.com/joho/godotenv"
  version = "^1.1.0"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "^1.1.4"

[[constraint]]
  branch = "master"
  name = "github.com/spf13/afero"

[[constraint]]
  name = "github.com/urfave/cli"
  version = "^1.19.1"

[[constraint]]
  branch = "master"
  name = "golang.org/x/net"

[[constraint]]
  branch = "master"
  name = "golang.org/x/oauth2"

[[constraint]]
  branch = "master"
  name = "google.golang.org/api"

[[constraint]]
  branch = "v2"
  name = "gopkg.in/yaml.v2"

[[constraint]]
  name = "k8s.io/client-go"
  version = "^3.0.0"
